# -*- mode: ruby -*-
# vi: set ft=ruby :

$name = 'vireo-centos'

$port = 9001

Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'

  config.ssh.insert_key = false

  config.vm.hostname = $name

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpuexecutioncap', '50']
    vb.customize ['setextradata', :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/#{$name}", '1']
    vb.name = $name
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network 'forwarded_port', guest: 9000, host: $port, protocol: 'tcp'

  config.vm.provision 'shell', inline: <<-SHELL
    yum install -y epel-release java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64 gcc-c++ wget

    wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
    yum install -y apache-maven

    yum install -y nodejs ruby ruby-devel git

    npm install -g bower
  SHELL

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    gem install compass --no-ri --no-rdoc

    git clone -b 4.0.x-sprint23-staging-npm-no-bin-links https://github.com/TexasDigitalLibrary/Vireo.git

    cd Vireo
    mvn clean compile
  SHELL

  config.vm.synced_folder 'src/Vireo', '/home/vagrant/Vireo', id: $name, create: true, mount_options: ['dmode=777', 'fmode=777']
end
