# -*- mode: ruby -*-
# vi: set ft=ruby :

$name = 'vireo-oracle'

$host_port = 9000

$branch = '4.0.x-sprint23-staging-npm-no-bin-links'

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/oracle-7.3'

  config.ssh.insert_key = false

  config.vm.hostname = $name

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpuexecutioncap', '50']
    vb.customize ['setextradata', :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/#{$name}", '1']
    vb.name = $name
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network 'forwarded_port', guest: 9000, host: $host_port, protocol: 'tcp'

  config.vm.provision 'shell', inline: <<-SHELL
    rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum install -y java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64 gcc-c++ wget yum-utils

    yum-config-manager --enable ol7_optional_latest

    yum install -y maven nodejs ruby ruby-devel git

    npm install -g bower
  SHELL

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    gem install compass --no-ri --no-rdoc

    git clone -b $branch https://github.com/TexasDigitalLibrary/Vireo.git

    cd Vireo
    mvn clean compile
  SHELL

  config.vm.synced_folder 'src/Vireo', '/home/vagrant/Vireo', id: $name, create: true, mount_options: ['dmode=777', 'fmode=777']
end
