# -*- mode: ruby -*-
# vi: set ft=ruby :

$name = 'vireo-ubuntu'

$host_port = 9000

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.ssh.insert_key = false

  config.vm.hostname = $name

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpuexecutioncap', '50']
    vb.customize ['setextradata', :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/#{$name}", '1']
    vb.name = $name
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.network 'forwarded_port', guest: 9000, host: $host_port, protocol: 'tcp'

  config.vm.provision 'shell', inline: <<-SHELL
    apt-add-repository -y ppa:openjdk-r/ppa
    apt-add-repository -y ppa:brightbox/ruby-ng

    apt-get uninstall ruby

    apt-get update

    apt-get install -y openjdk-8-jdk ruby2.2 ruby-dev maven git

    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    apt-get install -y nodejs

    npm install -g npm
    npm install -g bower

    gem install compass --no-ri --no-rdoc
  SHELL

  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    git clone -b 4.0.x https://github.com/TexasDigitalLibrary/Vireo.git

    cd Vireo
    mvn clean compile
  SHELL

  config.vm.synced_folder 'src/Vireo', '/home/vagrant/Vireo', id: $name, create: true, mount_options: ['dmode=777', 'fmode=777']
end
